UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Коровник Простор';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Мастерская в Миренках';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику БАЗА МИРЕНКИ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику КАДАСТРОВЫЕ УСЛУГИ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику КРОВЛЯ СКЛАДА МИРЕНКИ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику КРЫША СКЛАДА В КРАСНОМ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику МАСТЕРСКАЯ В ПРОСТОРЕ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ОБОРУДОВАНИЕ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ОБОРУДОВАНИЕ И РАСХОДНЫЕ МАТЕРИАЛЫ ДЛЯ РЕМОНТА';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ОБОРУДОВАНИЕ ЭЛЕКТРИКА ИНСТРУМЕНТ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ОСНОВНЫЕ СРЕДСТВА';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ОСНОВНЫЕ СРЕДСТВА (кредит)';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ПО 1С';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ПО СБИС';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ПОКУПКА ЗДАНИЙ И СООРУЖЕНИЙ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ПОКУПКА ЗЕМЛИ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ПОЛЫ СКЛАД МИРЕНКИ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику Постройка плотины в Заречном';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ПРОЧЕЕ ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ПРОЧИЕ ЦИФРОВЫЕ СЕРВИСЫ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику РЕМОНТ ЗЕРНОХРАНИЛИЩА МИРЕНКИ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику Ремонт склада запчастей КРАСНОЕ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику Система Видеонаблюдения';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику СКЛАД В ЗАРЕЧНОМ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику Стройматериалы';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ТЕХНИКА И ОБОРУДОВАНИЕ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ТО';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику УСЛУГИ РЕМОНТА';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику услуги ремонта (кредит)';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ЦЕХ ПО РЕМОНТУ ТЕХНИКИ МИРЕНКИ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ЦИФРОВЫЕ СЕРВИСЫ (АГРОСИГНАЛ)';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ЦИФРОВЫЕ СЕРВИСЫ (ВИАЛОН)';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ЦИФРОВЫЕ СЕРВИСЫ (СКАЙ ТЕЛЕКОМ)';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'ОФИС В ЗАРЕЧНОМ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'Перечисление подотчетному лицу УСЛУГИ РЕМОНТА';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'ПОКУПКА ОФИСНОГО И ИНОГО ОБОРУДОВАНИЯ И ОРГТЕХНИКИ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'РЕМОНТ ФЕРМЫ КРС В ПРОСТОРЕ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'ТОКАРНАЯ МИРЕНКИ';
UPDATE outcome_articles SET is_investment = 1 WHERE article_name = 'ЦИФРОВЫЕ СЕРВИСЫ (ПРОЧЕЕ ЦС)';

UPDATE income_articles SET is_investment = 1 WHERE article_name = 'Оплата поставщику ОСНОВНЫЕ СРЕДСТВА';
UPDATE income_articles SET is_investment = 1 WHERE article_name = 'Поступления от покупателей РЕАЛИЗАЦИЯ ОС';

